#spring:
#  jpa:
#    database: postgresql
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  datasource:
#    url: jdbc:postgresql://localhost:5432/member
#    username: postgres
#    password:
#    driver-class-name: org.postgresql.Driver